### PR TITLE
add integration test for kafka

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
@bzwei @benthomasson pls review

**Comment by bzwei** [comment]
@Alex-Izquierdo Looks good. How long does the integration test takes for each run?

**Comment by Alex-Izquierdo** [comment]
@bzwei two minutes: example:  https://github.com/Alex-Izquierdo/benthomasson-eda/actions/runs/2868978941

**Comment by benthomasson** [comment]
@Alex-Izquierdo please rebase

**Review by benthomasson — APPROVED** [review]

**Pull request merged**
